set-option -g default-terminal 'tmux-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^A
set -g base-index 1           # start indexing windoes at 1 instead of 0
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g escape-time 0          # zero-out escape time delay
set -g history-limit 1000000  # increase history size (from 2,000)
set -g renumber-windows on    # renumber all windows when any window is closed
set -g set-clipboard on       # use system clipboard

bind C-y display-popup -d "#{pane_current_path}" -E "bash"
bind C split-window -v -c "#{pane_current_path}" "claude --dangerously-skip-permissions"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

run '~/.tmux/plugins/tpm/tpm'
